/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Core: typeof import('./src/layout/core/index.vue')['default']
    Footer: typeof import('./src/layout/core/Footer/Footer.vue')['default']
    Header: typeof import('./src/layout/core/Header/Header.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    Main: typeof import('./src/layout/core/Main/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
